from enum import StrEnum


class RuleType(StrEnum):
    SAFETY = "SAFETY"
    EXCLUSION = "EXCLUSION"
    ELIGIBILITY = "ELIGIBILITY"
    TEST_SELECTION = "TEST_SELECTION"
    EXERCISE_SELECTION = "EXERCISE_SELECTION"
    PRESCRIPTION = "PRESCRIPTION"
    VOLUME = "VOLUME"
    INTENSITY = "INTENSITY"
    REST = "REST"
    FREQUENCY = "FREQUENCY"
    SCHEDULING = "SCHEDULING"
    PROGRESSION = "PROGRESSION"
    REGRESSION = "REGRESSION"
    DELOAD = "DELOAD"
    REEVALUATION = "REEVALUATION"
    WARNING = "WARNING"
    PREFERENCE = "PREFERENCE"


class ActionType(StrEnum):
    INCLUDE_EXERCISE = "INCLUDE_EXERCISE"
    EXCLUDE_EXERCISE = "EXCLUDE_EXERCISE"
    INCLUDE_CATEGORY = "INCLUDE_CATEGORY"
    EXCLUDE_CATEGORY = "EXCLUDE_CATEGORY"
    SET_SETS = "SET_SETS"
    SET_REPS = "SET_REPS"
    SET_DURATION = "SET_DURATION"
    SET_INTENSITY = "SET_INTENSITY"
    SET_REST = "SET_REST"
    SET_MIN = "SET_MIN"
    SET_MAX = "SET_MAX"
    MULTIPLY_VOLUME = "MULTIPLY_VOLUME"
    SET_FREQUENCY = "SET_FREQUENCY"
    SET_LOAD = "SET_LOAD"
    SET_LOAD_PERCENT = "SET_LOAD_PERCENT"
    SET_RPE = "SET_RPE"
    SET_RIR = "SET_RIR"
    ALLOW_PROGRESSION = "ALLOW_PROGRESSION"
    BLOCK_PROGRESSION = "BLOCK_PROGRESSION"
    TRIGGER_DELOAD = "TRIGGER_DELOAD"
    TRIGGER_REEVALUATION = "TRIGGER_REEVALUATION"
    SHOW_WARNING = "SHOW_WARNING"


class Operator(StrEnum):
    EQ = "EQ"
    NEQ = "NEQ"
    GT = "GT"
    GTE = "GTE"
    LT = "LT"
    LTE = "LTE"
    BETWEEN = "BETWEEN"
    IN = "IN"
    NOT_IN = "NOT_IN"
    EXISTS = "EXISTS"
    NOT_EXISTS = "NOT_EXISTS"


class PackageStatus(StrEnum):
    DRAFT = "DRAFT"
    RESEARCH = "RESEARCH"
    TESTING = "TESTING"
    ACTIVE = "ACTIVE"
    DEPRECATED = "DEPRECATED"
    ARCHIVED = "ARCHIVED"


PRECEDENCE = {
    RuleType.SAFETY: 500,
    RuleType.EXCLUSION: 400,
    RuleType.ELIGIBILITY: 300,
    RuleType.PRESCRIPTION: 200,
    RuleType.PREFERENCE: 100,
}
